project:
  type: website

website:
  title: "Accessible lecture notes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - chirun.qmd
      - quarto.qmd
      - blackboard.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



