---
title: "Chirun"
---

## Introduction

[Chirun](https://chirun.org.uk/) is a system to convert LaTeX notes to
a range of formats, includingn html.  Here is the [Chirun
documentation](https://chirun.org.uk/docs/): Chirun is in development
and the documentation may be incomplete.  Chirun can be run either
with a Python package (requiring
[installation](https://chirun.org.uk/docs/en/latest/cli/install.html)),
or an [online interface](https://lti.chirun.org.uk/) (not requiring
installation). I will describe using the online interface below.

## Using the online interface to Chirun

1. Compress the folder containing LaTeX notes to a zip file. As an
   example, we will use the [simple example LaTeX
   notes](https://github.com/heogden/simple).
   You can download a zip file of these
   example notes,
   [simple-main.zip](https://github.com/heogden/simple/archive/refs/heads/main.zip).

2. Go to [lti.chirun.org.uk](https://lti.chirun.org.uk/) and click
   "Create a new package". Upload the zip file (e.g. simple-main.zip)
   to the "Upload files" section. 
   
3. You will be prompted to configure Chirun.  Under "Package
   settings", you are asked for some basic information (title, author,
   etc.). After completing this, delete the input files which are not
   standalone documents, and are included as sections or chapters of
   notes. In our example, we click on each of "01-determinant.tex",
   "preface.tex" and "02-variance.tex" then press the "Delete this
   item" button. The only file we keep in this case is
   "notes.tex". Click on "notes.tex", and change the type to
   "Document". You can change the title to something more informative.
   
4. Press "Save" and Chirun will attempt to build your notes (this may
   take some time).

5. In the simple example, the notes build without errors, but often
   you will get an error on the first attempt and will need to make
   some changes to your notes (see
   [Troubleshooting](chirun.qmd#troubleshooting)).
   
6. If the build succeeds, you can view the html lecture notes. 
   
7. You can also download your lecture notes as processed by Chirun as
   a zip file. This is also useful for [uploading to
   blackboard](blackboard.qmd).

You can save your configuration, to avoid having to repeat step 3
every time you run Chirun (e.g. if you make a change to your
notes). To do this, extract the downloaded zip file from step 7, and
copy the file "MANIFEST.yml" into the folder with your LaTeX sources
files. Rename this file to "config.yml". If you follow the steps
again, your previous configuration will be saved, and you can skip
over step 3.

   
## Troubleshooting

Here are some issues I have encountered when using Chirun:
   
- Chirun is not able to use some LaTeX packages. You may have to
   simplify your LaTeX code to avoid using such packages. You can try to
   track down packages causing problems by looking in the build log. For
   instance, if I tried to use the fourier package, the build would
   encounter an error.  If I looked in the build log, at some point I
   would see:

	```
	WARNING: No Python version of fourier.sty was found 
	WARNING: Will now try to load a LaTeX implementation of fourier.sty 
	``` 
	which indicates that I should try removing the fourier package.
	Chirun error messages are not always clear, but I have found that
	searching for the DEBUG section then looking for the first WARNING is
	useful to track down packages causing problems.

- Chirun does not work with including pdfs. You will need to convert
   any graphics included as pdfs to an image format (e.g. png) first.

- Chirun sometimes has problems processing tables correctly. You may
   need to simplify the structure of tables.
 
- For referencing, Chirun works fine with bibtex, but not biblatex.

 

