---
title: "Creating accessible mathematical lecture notes"
---

This is an in-development guide for writing accessible lecture notes
in Mathematical Sciences. Our notes are typically written in LaTeX,
and provided to students in pdf format. At the moment, equations in
pdfs are typically [not correctly interpreted by screen
readers](https://youtu.be/BsTqEjTIILQ). The content is displayed in a
fixed format, and often that format is difficult for dyslexic people
to read (see the [Dyslexia friendly style
guide](https://www.bdadyslexia.org.uk/advice/employers/creating-a-dyslexia-friendly-workplace/dyslexia-friendly-style-guide)
for advice on this).

The main focus of this guide is on methods to provide notes in html
format. Screen readers can handle MathJax equations in html, and the
html output from the tools described below is typically easier to read
for dyslexic people than pdfs produced by LaTeX. Providing notes in
html format will not fix all accessibility issues, but it is a good
place to start.

To demonstrate methods, I will use some [simple example LaTeX
   notes](https://github.com/heogden/simple) (which are based on
   material from Wikipedia). Here is the [pdf version of the
   notes](https://heogden.github.io/simple-chirun/lecture_notes/pdf/notes.pdf).

I will give instructions on how to use two systems to convert to html
format:

- [Chirun](chirun.qmd) is a good option if you want to continue to
write your notes in LaTeX. It has a relatively easy-to-use online
interface which means it can be used without installing anything on
your own computer. Chirun is under development and the
[documentation](https://chirun.org.uk/docs/) is currently incomplete.
Here are the [example notes from
Chirun](https://heogden.github.io/simple-chirun). Chirun is
specifically focused on accessibility, and allows users to change the
font, spacing and background colour which may be helpful for dyslexic
students.

- [Quarto](quarto.qmd) is is a good option if you are happy to convert
your LaTeX notes into markdown format, then work with the markdown
notes (rather than the original LaTeX source) from then on. It is
based on R Markdown, but is designed for a wider range of users, and
you can include R or python code easily. Quarto is well
[documented](https://quarto.org/docs/guide/). Here are the [example notes from
Quarto](https://heogden.github.io/simple-quarto).

Converting your real notes is likely to require substantially more
work than converting the simple example notes. It is likely that you
will need to simplify your original LaTeX code to get either system to
work, for instance reducing dependence on LaTeX packages.  Conversion
to Quarto is likely to require more changes than processing with
Chirun. 
   
I have also provided some guidance on [uploading html notes to
Blackboard](blackboard.qmd).
