---
title: "Quarto"
---


1. Create the structure for the notes using [this quick start guide on
   writing a Quarto book](https://quarto.org/docs/books/#quick-start).
   Edit the file _quarto.yml to match the structure of your
   notes. Replace the file "references.bib" with your own .bib file,
   and put the name of your .bib file in the bibliography seciton of
   _quarto.yml.
	
2. Convert files from .tex to markdown with pandoc. It is possible to
   do this online at: https://pandoc.org/try/. Choose from "latex" to
   "markdown". Copy and paste output into a .qmd file with same name
   as each Chapter's .tex file. The content which you would like to
   appear on the first page when the notes are viewed should appear in
   a file called index.qmd.
   
3. At this stage, you can run quarto to preview the output. If you are
   using RStudio, you can press the "Render" button. From the command
   line, type "quarto render".
   
4. There are likely to be problems with the output. Here are
   problems which needed fixing with the simple example notes:

	a) The default attempt at cross referencing from the pandoc output
    is not correct. The correct way to cross reference is [documented
    here](https://quarto.org/docs/authoring/cross-references.html).
    There is a strict structure for where to put the labels and for
    the names of the labels: for instance, Figures need to have labels
    starting fig-, Tables need to have labels starting tbl-. Avoid the
    use of underscores in labels.
	
	b) The default conversion of tables does not always work well.
	Try copying the LaTeX table code to pandoc online, then convert
	from "latex" to "markdown-mmd", and replace the initial attempt at
	the markdown table with this one. After that, you will still need
	to fix the label for the table.
	
	c) The default conversion of AMS theorem-type environments does
	not work well, but it is fairly easy to fix this, as [documented
	here](https://quarto.org/docs/authoring/cross-references.html#theorems-and-proofs)

5. Once the preview of the output is looking good, you can try
   creating the html and pdf versions by typing "quarto render" in the
   terminal. You may get errors at this stage. In the simple example
   notes, I got an error, which was fixed by explicitly stating the
   file ending of included graphics files.
